/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PenIndexRouteImport } from './routes/pen.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as PenOrdersRouteImport } from './routes/pen.orders'
import { Route as PenLoginRouteImport } from './routes/pen.login'
import { Route as PenCategoriesRouteImport } from './routes/pen.categories'
import { Route as PenProductsIndexRouteImport } from './routes/pen.products.index'
import { Route as PenProductsNewRouteImport } from './routes/pen.products.new'
import { Route as PenProductsIdEditRouteImport } from './routes/pen.products.$id.edit'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PenIndexRoute = PenIndexRouteImport.update({
  id: '/pen/',
  path: '/pen/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PenOrdersRoute = PenOrdersRouteImport.update({
  id: '/pen/orders',
  path: '/pen/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PenLoginRoute = PenLoginRouteImport.update({
  id: '/pen/login',
  path: '/pen/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PenCategoriesRoute = PenCategoriesRouteImport.update({
  id: '/pen/categories',
  path: '/pen/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const PenProductsIndexRoute = PenProductsIndexRouteImport.update({
  id: '/pen/products/',
  path: '/pen/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PenProductsNewRoute = PenProductsNewRouteImport.update({
  id: '/pen/products/new',
  path: '/pen/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PenProductsIdEditRoute = PenProductsIdEditRouteImport.update({
  id: '/pen/products/$id/edit',
  path: '/pen/products/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/shop': typeof ShopRoute
  '/pen/categories': typeof PenCategoriesRoute
  '/pen/login': typeof PenLoginRoute
  '/pen/orders': typeof PenOrdersRoute
  '/product/$slug': typeof ProductSlugRoute
  '/pen/': typeof PenIndexRoute
  '/pen/products/new': typeof PenProductsNewRoute
  '/pen/products/': typeof PenProductsIndexRoute
  '/pen/products/$id/edit': typeof PenProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/shop': typeof ShopRoute
  '/pen/categories': typeof PenCategoriesRoute
  '/pen/login': typeof PenLoginRoute
  '/pen/orders': typeof PenOrdersRoute
  '/product/$slug': typeof ProductSlugRoute
  '/pen': typeof PenIndexRoute
  '/pen/products/new': typeof PenProductsNewRoute
  '/pen/products': typeof PenProductsIndexRoute
  '/pen/products/$id/edit': typeof PenProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/shop': typeof ShopRoute
  '/pen/categories': typeof PenCategoriesRoute
  '/pen/login': typeof PenLoginRoute
  '/pen/orders': typeof PenOrdersRoute
  '/product/$slug': typeof ProductSlugRoute
  '/pen/': typeof PenIndexRoute
  '/pen/products/new': typeof PenProductsNewRoute
  '/pen/products/': typeof PenProductsIndexRoute
  '/pen/products/$id/edit': typeof PenProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/order-confirmed'
    | '/shop'
    | '/pen/categories'
    | '/pen/login'
    | '/pen/orders'
    | '/product/$slug'
    | '/pen/'
    | '/pen/products/new'
    | '/pen/products/'
    | '/pen/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/order-confirmed'
    | '/shop'
    | '/pen/categories'
    | '/pen/login'
    | '/pen/orders'
    | '/product/$slug'
    | '/pen'
    | '/pen/products/new'
    | '/pen/products'
    | '/pen/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/order-confirmed'
    | '/shop'
    | '/pen/categories'
    | '/pen/login'
    | '/pen/orders'
    | '/product/$slug'
    | '/pen/'
    | '/pen/products/new'
    | '/pen/products/'
    | '/pen/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  ShopRoute: typeof ShopRoute
  PenCategoriesRoute: typeof PenCategoriesRoute
  PenLoginRoute: typeof PenLoginRoute
  PenOrdersRoute: typeof PenOrdersRoute
  ProductSlugRoute: typeof ProductSlugRoute
  PenIndexRoute: typeof PenIndexRoute
  PenProductsNewRoute: typeof PenProductsNewRoute
  PenProductsIndexRoute: typeof PenProductsIndexRoute
  PenProductsIdEditRoute: typeof PenProductsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pen/': {
      id: '/pen/'
      path: '/pen'
      fullPath: '/pen/'
      preLoaderRoute: typeof PenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pen/orders': {
      id: '/pen/orders'
      path: '/pen/orders'
      fullPath: '/pen/orders'
      preLoaderRoute: typeof PenOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pen/login': {
      id: '/pen/login'
      path: '/pen/login'
      fullPath: '/pen/login'
      preLoaderRoute: typeof PenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pen/categories': {
      id: '/pen/categories'
      path: '/pen/categories'
      fullPath: '/pen/categories'
      preLoaderRoute: typeof PenCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pen/products/': {
      id: '/pen/products/'
      path: '/pen/products'
      fullPath: '/pen/products/'
      preLoaderRoute: typeof PenProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pen/products/new': {
      id: '/pen/products/new'
      path: '/pen/products/new'
      fullPath: '/pen/products/new'
      preLoaderRoute: typeof PenProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pen/products/$id/edit': {
      id: '/pen/products/$id/edit'
      path: '/pen/products/$id/edit'
      fullPath: '/pen/products/$id/edit'
      preLoaderRoute: typeof PenProductsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  ShopRoute: ShopRoute,
  PenCategoriesRoute: PenCategoriesRoute,
  PenLoginRoute: PenLoginRoute,
  PenOrdersRoute: PenOrdersRoute,
  ProductSlugRoute: ProductSlugRoute,
  PenIndexRoute: PenIndexRoute,
  PenProductsNewRoute: PenProductsNewRoute,
  PenProductsIndexRoute: PenProductsIndexRoute,
  PenProductsIdEditRoute: PenProductsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
